joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster


joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      elbow_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
    speed_scaling_interface_name: speed_scaling/speed_scaling_factor

io_and_status_controller:
  ros__parameters:
    type: ur_controllers/GPIOController
    tf_prefix: ""

ur_configuration_controller:
  ros__parameters:
    type: ur_controllers/URConfigurationController
    tf_prefix: ""

force_torque_sensor_broadcaster:
  ros__parameters:
    type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster
    sensor_name: tcp_fts_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: tool0
    topic_name: ft_data

passthrough_trajectory_controller:
  ros__parameters:
    type: ur_controllers/PassthroughTrajectoryController
    tf_prefix: ""
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    state_interfaces:
      - position
      - velocity
    speed_scaling_interface_name: speed_scaling/speed_scaling_factor

gripper_position_controller:
  ros__parameters:
    type: parallel_gripper_action_controller/GripperActionController
    joint: gripper_finger_right
    goal_tolerance: 0.001

force_mode_controller:
  ros__parameters:
    type: ur_controllers/ForceModeController
    tf_prefix: ""

freedrive_mode_controller:
  ros__parameters:
    type: ur_controllers/FreedriveModeController
    tf_prefix: ""

tcp_pose_broadcaster:
  ros__parameters:
    type: pose_broadcaster/PoseBroadcaster
    frame_id: base
    pose_name: tcp_pose
    tf:
      child_frame_id: tool0_controller

tool_contact_controller:
  ros__parameters:
    type: ur_controllers/ToolContactController
    tf_prefix: ""