services:
  ros-container:
    image: ${IMAGE_TAG_FULL}
    container_name: ${CONTAINER_NAME}
    hostname: ${CONTAINER_NAME}
    restart: "no"
    networks:
      ctrlx_bridge:
      ctrlx_macvtap:
        ipv4_address: ${CONTAINER_MACVLAN_IP}
    
    # x11 forwarding for graphics applications
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
    
    # allow container to be interactive
    stdin_open: true
    tty: true
    # keep container running
    command: tail -f /dev/null

networks:
  # to access host network, can be turned off if not necessary
  ctrlx_bridge:
    name: ${CONTAINER_NAME}-bridge
    driver: bridge

  ctrlx_macvtap:
    driver: macvlan
    name: ${CONTAINER_NAME}-macvtap
    driver_opts:
      parent: ${HOST_NETWORK_INTERFACE}
    ipam:
      config:
        - subnet: 192.168.28.0/24