# Docker Compose file for the ROS 2 commissioning environment.
# This setup uses a macvlan network to allow the container to communicate
# directly with the ctrlX CORE device on the local network.

services:
  ros-container:
    image: ${IMAGE_TAG_FULL}
    container_name: ${CONTAINER_NAME}
    hostname: ${CONTAINER_NAME}
    restart: "no"
    networks:
      ctrlx_bridge:
      ctrlx_macvtap:
        ipv4_address: ${CONTAINER_MACVLAN_IP}
    
    # --- X11 Forwarding for GUI Applications (e.g., RViz) ---
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Note: You may need to configure xauth on your host for this to work.
      # xhost +local:docker
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      
    devices:
      - /dev/dri:/dev/dri
    
    # allow container to be interactive
    stdin_open: true
    tty: true
    # keep container running
    command: tail -f /dev/null

networks:
  # This accesses host's network, can remove if not necessary
  ctrlx_bridge:
    name: ${CONTAINER_NAME}-bridge
    driver: bridge

  # This taps into the host's physical network interface.
  ctrlx_macvtap:
    driver: macvlan
    name: ${CONTAINER_NAME}-macvtap
    driver_opts:
      parent: ${HOST_NETWORK_INTERFACE}
    ipam:
      config:
        - subnet: 192.168.28.0/24