/**:
  ros__parameters:
    robot_description_planning:
      joint_limits:
        fr3_left_joint1:
          has_velocity_limits: true
          max_velocity: 2.5
          has_acceleration_limits: true
          max_acceleration: 15.0
        fr3_left_joint2:
          has_velocity_limits: true
          max_velocity: 2.5
          has_acceleration_limits: true
          max_acceleration: 7.5
        fr3_left_joint3:
          has_velocity_limits: true
          max_velocity: 2.5
          has_acceleration_limits: true
          max_acceleration: 10.0
        fr3_left_joint4:
          has_velocity_limits: true
          max_velocity: 2.5
          has_acceleration_limits: true
          max_acceleration: 12.5
        fr3_left_joint5:
          has_velocity_limits: true
          max_velocity: 2.5
          has_acceleration_limits: true
          max_acceleration: 15.0
        fr3_left_joint6:
          has_velocity_limits: true
          max_velocity: 2.5
          has_acceleration_limits: true
          max_acceleration: 20.0
        fr3_left_joint7:
          has_velocity_limits: true
          max_velocity: 2.5
          has_acceleration_limits: true
          max_acceleration: 20.0
        fr3_right_joint1:
          has_velocity_limits: true
          max_velocity: 2.5
          has_acceleration_limits: true
          max_acceleration: 15.0
        fr3_right_joint2:
          has_velocity_limits: true
          max_velocity: 2.5
          has_acceleration_limits: true
          max_acceleration: 7.5
        fr3_right_joint3:
          has_velocity_limits: true
          max_velocity: 2.5
          has_acceleration_limits: true
          max_acceleration: 10.0
        fr3_right_joint4:
          has_velocity_limits: true
          max_velocity: 2.5
          has_acceleration_limits: true
          max_acceleration: 12.5
        fr3_right_joint5:
          has_velocity_limits: true
          max_velocity: 2.5
          has_acceleration_limits: true
          max_acceleration: 15.0
        fr3_right_joint6:
          has_velocity_limits: true
          max_velocity: 2.5
          has_acceleration_limits: true
          max_acceleration: 20.0
        fr3_right_joint7:
          has_velocity_limits: true
          max_velocity: 2.5
          has_acceleration_limits: true
          max_acceleration: 20.0
