# Example command to transition states:
#
# ros2 action send_goal --feedback /foreman/set_profile foreman_msgs/action/SetProfile "{profile: 'inactive'}"
#

transition_pause: 0.5

hardware:
  - fr3_FrankaHardwareInterface

controllers:
  fr3_joint_trajectory_controller:
    requires: [fr3_FrankaHardwareInterface, active]
  joint_state_broadcaster:
    requires: [fr3_FrankaHardwareInterface, active]

profiles:

  inactive:
    controllers:
      fr3_joint_trajectory_controller: inactive
      joint_state_broadcaster: inactive
    hardware:
      fr3_FrankaHardwareInterface: inactive

  active:
    controllers:
      fr3_joint_trajectory_controller: active
      joint_state_broadcaster: active
    hardware:
      fr3_FrankaHardwareInterface: active
